api_version = "2024-07"

[[extensions]]
uid = "fbb1d285-3fb9-f44d-06bc-ddccc071c32b755d35b1"
type = "payments_extension"
name = "Georgia Pay Offsite"
handle = "georgia-pay-offsite"
merchant_label = "Georgia Pay (TBC & BOG)"
buyer_label = "Pay with Georgian bank (GEL)"
payment_session_url = "https://laripay.vercel.app/api/payment_session"
refund_session_url = "https://laripay.vercel.app/api/refund_session"
supported_countries = ["GE"]
supported_payment_methods = ["visa", "master", "american_express"]
test_mode_available = true
supports_3ds = false
supports_installments = false
supports_deferred_payments = false
multiple_capture = false

[[extensions.targeting]]
target = "payments.offsite.render"
